import type { Scenario, Badge } from "./schema";

export const availableBadges: Badge[] = [
  {
    id: "security_aware",
    name: "Security Aware",
    description: "Completed your first scenario without major security incidents",
    icon: "shield",
  },
  {
    id: "vpn_master",
    name: "VPN Master",
    description: "Consistently used VPN protection on public networks",
    icon: "lock",
  },
  {
    id: "network_detective",
    name: "Network Detective",
    description: "Successfully identified a trap network",
    icon: "search",
  },
  {
    id: "patient_professional",
    name: "Patient Professional",
    description: "Postponed sensitive tasks until reaching a secure network",
    icon: "clock",
  },
  {
    id: "perfect_score",
    name: "Perfect Score",
    description: "Completed a scenario with zero risk points",
    icon: "star",
  },
];

export const scenarios: Scenario[] = [
  {
    id: "coffee_shop_beginner",
    title: "Morning at The Daily Grind",
    description: "You've stopped at your favorite coffee shop before an important meeting. You need to check a few things online, but which network should you trust?",
    location: "The Daily Grind Coffee Shop",
    difficulty: "beginner",
    estimatedTime: "5 minutes",
    startSceneId: "arrival_1",
    scenes: [
      {
        id: "arrival_1",
        type: "arrival",
        title: "Welcome to The Daily Grind",
        description: "You settle into a comfortable corner seat with your latte. Your laptop is open and you see several Wi-Fi networks available. You have 30 minutes before your meeting.",
        location: "The Daily Grind Coffee Shop",
        nextSceneId: "network_select_1",
      },
      {
        id: "network_select_1",
        type: "network_selection",
        title: "Choose a Network",
        description: "Several networks appear on your screen. The coffee shop has a sign on the counter, but you can't quite read it from here.",
        location: "The Daily Grind Coffee Shop",
        networks: [
          {
            id: "net_official",
            ssid: "DailyGrind_Guest",
            signalStrength: 5,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            verifiedByStaff: true,
            riskLevel: "safe",
            description: "Official coffee shop network",
          },
          {
            id: "net_fake",
            ssid: "FREE_Daily_Grind_WiFi",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "Suspicious network with similar name",
          },
          {
            id: "net_open",
            ssid: "FreePublicWiFi",
            signalStrength: 3,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "Generic open network - could be anyone",
          },
          {
            id: "net_neighbor",
            ssid: "Bookstore_Next_Door",
            signalStrength: 2,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "suspicious",
            description: "Neighboring business network",
          },
        ],
        actions: [
          { id: "verify", type: "verify_staff", label: "Ask staff for the correct network", description: "Walk to the counter and confirm the official Wi-Fi name", isPrimary: true },
        ],
        choices: [
          { actionId: "connect_official", nextSceneId: "task_email" },
          { actionId: "connect_fake", nextSceneId: "consequence_trap" },
          { actionId: "connect_open", nextSceneId: "consequence_open" },
          { actionId: "connect_neighbor", nextSceneId: "consequence_neighbor" },
          { actionId: "verify", nextSceneId: "verified_network" },
        ],
      },
      {
        id: "verified_network",
        type: "network_selection",
        title: "Staff Confirmation",
        description: "The barista confirms: 'Our official network is DailyGrind_Guest. The password is on your receipt!' They also mention they've seen some fake networks pop up recently.",
        location: "The Daily Grind Coffee Shop",
        networks: [
          {
            id: "net_official",
            ssid: "DailyGrind_Guest",
            signalStrength: 5,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            verifiedByStaff: true,
            riskLevel: "safe",
            description: "Official coffee shop network - VERIFIED",
          },
          {
            id: "net_fake",
            ssid: "FREE_Daily_Grind_WiFi",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "SUSPICIOUS - Not the official network!",
          },
        ],
        choices: [
          { actionId: "connect_official_verified", nextSceneId: "task_email_verified" },
        ],
      },
      {
        id: "task_email_verified",
        type: "task_prompt",
        title: "Check Your Email",
        description: "You're connected to the verified official network. Now you need to check your email for the meeting agenda.",
        location: "The Daily Grind Coffee Shop",
        task: {
          id: "task_check_email",
          type: "email",
          title: "Check Work Email",
          description: "Open your email to review the meeting agenda that was sent this morning.",
          sensitivityLevel: "medium",
          riskHint: "Email accounts often contain sensitive information and password reset links.",
        },
        actions: [
          { id: "proceed_email", type: "proceed", label: "Check email now", isPrimary: true },
          { id: "use_vpn_email", type: "use_vpn", label: "Enable VPN first, then check email" },
          { id: "postpone_email", type: "postpone", label: "Wait until you're on a more secure network" },
        ],
        choices: [
          { actionId: "proceed_email", nextSceneId: "consequence_email_safe" },
          { actionId: "use_vpn_email", nextSceneId: "consequence_email_vpn" },
          { actionId: "postpone_email", nextSceneId: "consequence_email_postponed" },
        ],
      },
      {
        id: "task_email",
        type: "task_prompt",
        title: "Check Your Email",
        description: "You're connected. Now you need to check your email for the meeting agenda.",
        location: "The Daily Grind Coffee Shop",
        task: {
          id: "task_check_email",
          type: "email",
          title: "Check Work Email",
          description: "Open your email to review the meeting agenda that was sent this morning.",
          sensitivityLevel: "medium",
          riskHint: "Email accounts often contain sensitive information and password reset links.",
        },
        actions: [
          { id: "proceed_email", type: "proceed", label: "Check email now", isPrimary: true },
          { id: "use_vpn_email", type: "use_vpn", label: "Enable VPN first, then check email" },
          { id: "postpone_email", type: "postpone", label: "Wait until you're on a more secure network" },
        ],
        choices: [
          { actionId: "proceed_email", nextSceneId: "task_banking" },
          { actionId: "use_vpn_email", nextSceneId: "task_banking_vpn" },
          { actionId: "postpone_email", nextSceneId: "consequence_email_postponed" },
        ],
      },
      {
        id: "task_banking",
        type: "task_prompt",
        title: "Quick Banking Task",
        description: "While checking email, you remember you need to transfer money to cover a bill due today.",
        location: "The Daily Grind Coffee Shop",
        task: {
          id: "task_banking",
          type: "banking",
          title: "Transfer Funds",
          description: "Log into your bank to transfer $200 to cover an upcoming bill payment.",
          sensitivityLevel: "critical",
          riskHint: "Banking involves your most sensitive financial credentials.",
        },
        actions: [
          { id: "proceed_banking", type: "proceed", label: "Log into bank now", isDanger: true },
          { id: "use_vpn_banking", type: "use_vpn", label: "Enable VPN first" },
          { id: "postpone_banking", type: "postpone", label: "Handle this later on a secure network", isPrimary: true },
        ],
        choices: [
          { actionId: "proceed_banking", nextSceneId: "consequence_banking_risky" },
          { actionId: "use_vpn_banking", nextSceneId: "consequence_banking_vpn" },
          { actionId: "postpone_banking", nextSceneId: "consequence_banking_smart" },
        ],
      },
      {
        id: "task_banking_vpn",
        type: "task_prompt",
        title: "Quick Banking Task",
        description: "Your VPN is active. You remember you need to transfer money to cover a bill due today.",
        location: "The Daily Grind Coffee Shop",
        task: {
          id: "task_banking",
          type: "banking",
          title: "Transfer Funds",
          description: "Log into your bank to transfer $200 to cover an upcoming bill payment.",
          sensitivityLevel: "critical",
          riskHint: "Banking involves your most sensitive financial credentials.",
        },
        actions: [
          { id: "proceed_banking_vpn", type: "proceed", label: "Log into bank (VPN active)", isPrimary: true },
          { id: "postpone_banking", type: "postpone", label: "Still prefer to wait for home network" },
        ],
        choices: [
          { actionId: "proceed_banking_vpn", nextSceneId: "consequence_banking_vpn" },
          { actionId: "postpone_banking", nextSceneId: "consequence_banking_smart" },
        ],
      },
      {
        id: "consequence_trap",
        type: "consequence",
        title: "Network Trap Detected",
        description: "You connected to what appeared to be the coffee shop's network...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_trap",
          type: "credential_harvested",
          severity: "danger",
          title: "Fake Network Trap",
          whatHappened: "You connected to 'FREE_Daily_Grind_WiFi' - a fake network set up by an attacker. A convincing login page appeared asking for your email to 'access the internet.' Any credentials you entered were captured.",
          whyRisky: "Attackers often create networks with names similar to legitimate ones (called 'evil twin' attacks). Open networks with enticing names like 'FREE' are major red flags. The fake captive portal harvested your login credentials.",
          saferAlternative: "Always verify the exact network name with staff before connecting. Look for secured networks (with the lock icon) and be suspicious of networks that are open but claim to be from a business.",
          technicalExplanation: "Evil twin attacks work by broadcasting a stronger signal than the legitimate network, causing devices to connect automatically. The attacker then intercepts all traffic or presents fake login pages.",
          safetyPointsChange: 0,
          riskPointsChange: 30,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_open",
        type: "consequence",
        title: "Risky Connection",
        description: "You connected to an open network with a generic name...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_open",
          type: "privacy_leaked",
          severity: "warning",
          title: "Unprotected Network",
          whatHappened: "You connected to 'FreePublicWiFi' - a completely open network with no encryption. Anyone nearby could potentially see your unencrypted traffic.",
          whyRisky: "Open networks with generic names could be set up by anyone. Without encryption, your browsing activity, search queries, and any non-HTTPS data is visible to others on the same network.",
          saferAlternative: "Choose networks that require a password (showing a lock icon). Verify the network name with the establishment. If you must use an open network, enable a VPN immediately.",
          technicalExplanation: "On unencrypted networks, attackers can use packet sniffing tools to capture network traffic. While HTTPS protects the content of secure websites, metadata like which sites you visit is still visible.",
          safetyPointsChange: 0,
          riskPointsChange: 20,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_neighbor",
        type: "consequence",
        title: "Wrong Network",
        description: "You connected to a neighboring business's network...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_neighbor",
          type: "privacy_leaked",
          severity: "warning",
          title: "Unintended Network",
          whatHappened: "You connected to the bookstore next door's network. While not malicious, you're now on a network you didn't intend to use, and your traffic is going through their router.",
          whyRisky: "Even legitimate networks from other businesses route your traffic through equipment you don't control. The network administrator could potentially monitor traffic, and you have no agreement with them about data handling.",
          saferAlternative: "Take a moment to verify you're connecting to the intended network. If you're at a coffee shop, connect to the coffee shop's official network, not a neighboring business.",
          technicalExplanation: "Network administrators can log connection data and potentially inspect unencrypted traffic. Using the wrong network also means you're subject to their security practices (or lack thereof).",
          safetyPointsChange: 0,
          riskPointsChange: 10,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_email_safe",
        type: "consequence",
        title: "Email Checked",
        description: "You checked your email on the verified network...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_email_safe",
          type: "safe_browsing",
          severity: "success",
          title: "Reasonably Safe",
          whatHappened: "You checked your email on the verified official network. Since your email provider uses HTTPS, your login credentials and email content were encrypted.",
          whyRisky: "Even on legitimate networks, there's some risk. The network owner could potentially see that you're accessing your email service (metadata), even if they can't read the content.",
          saferAlternative: "For extra security, especially on any public network, use a VPN. This encrypts all your traffic and hides even the metadata about which services you're using.",
          technicalExplanation: "HTTPS encrypts the data between your browser and the email server, but DNS queries and connection metadata may still be visible to network observers.",
          safetyPointsChange: 10,
          riskPointsChange: 0,
        },
        nextSceneId: "task_banking",
      },
      {
        id: "consequence_email_vpn",
        type: "consequence",
        title: "VPN Protected",
        description: "You enabled your VPN before checking email...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_email_vpn",
          type: "vpn_protected",
          severity: "success",
          title: "Excellent Security Practice",
          whatHappened: "You enabled your VPN before accessing your email. All your traffic is now encrypted and routed through a secure tunnel, invisible to anyone on the coffee shop network.",
          whyRisky: "VPN usage on public Wi-Fi is a best practice. The only minor consideration is that you're trusting your VPN provider, so choose a reputable one.",
          saferAlternative: "You made the optimal choice! For maximum security, ensure your VPN is from a trusted provider with a no-logs policy.",
          technicalExplanation: "A VPN creates an encrypted tunnel between your device and the VPN server. All traffic appears as encrypted data to the local network, and your real IP address is hidden from websites.",
          safetyPointsChange: 20,
          riskPointsChange: 0,
        },
        nextSceneId: "task_banking_vpn",
      },
      {
        id: "consequence_email_postponed",
        type: "consequence",
        title: "Task Postponed",
        description: "You decided to wait on checking email...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_email_postponed",
          type: "action_postponed",
          severity: "success",
          title: "Cautious Approach",
          whatHappened: "You decided to postpone checking your email until you're on a more secure network. While perhaps overly cautious for just checking email, this eliminates any risk.",
          whyRisky: "This was a very safe choice. The trade-off is convenience - you'll need to check email later when you have a more secure connection.",
          saferAlternative: "For routine email checking on a verified network with HTTPS, proceeding with a VPN is a good balance of security and convenience.",
          technicalExplanation: "Postponing eliminates all network-based risks. For time-sensitive but non-critical tasks, using a VPN on the verified network is a reasonable compromise.",
          safetyPointsChange: 10,
          riskPointsChange: 0,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_banking_risky",
        type: "consequence",
        title: "Banking on Public Wi-Fi",
        description: "You accessed your bank account on the public network...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_banking_risky",
          type: "session_compromised",
          severity: "danger",
          title: "High-Risk Banking",
          whatHappened: "You logged into your bank on a public Wi-Fi network without VPN protection. While the bank uses HTTPS, this is still risky behavior that could expose you to sophisticated attacks.",
          whyRisky: "Public networks can be compromised in ways that intercept even HTTPS traffic (SSL stripping, certificate spoofing on misconfigured devices). Banking credentials are among the most valuable targets for attackers.",
          saferAlternative: "Never access banking on public Wi-Fi without a VPN. Better yet, postpone banking until you're on a trusted private network. If urgent, use your mobile data instead of public Wi-Fi.",
          technicalExplanation: "While modern HTTPS is secure, attackers on the same network could attempt downgrade attacks, DNS spoofing to fake bank sites, or exploit any misconfigurations in your browser's certificate validation.",
          safetyPointsChange: 0,
          riskPointsChange: 40,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_banking_vpn",
        type: "consequence",
        title: "Protected Banking",
        description: "You accessed your bank with VPN protection...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_banking_vpn",
          type: "vpn_protected",
          severity: "success",
          title: "Smart Security Choice",
          whatHappened: "You used a VPN before accessing your bank account. This adds a strong layer of encryption and prevents local network attacks from intercepting your traffic.",
          whyRisky: "Using a VPN for banking on public Wi-Fi is a good practice. The remaining risk is minimal - mainly trusting your VPN provider and ensuring you're on the real bank website.",
          saferAlternative: "For the most sensitive transactions, consider using your mobile data instead of any public Wi-Fi, even with a VPN. But your choice was a solid security decision.",
          technicalExplanation: "The VPN encrypts all traffic before it leaves your device, making it impossible for local network attackers to intercept or manipulate your bank connection.",
          safetyPointsChange: 25,
          riskPointsChange: 0,
        },
        nextSceneId: "completion",
      },
      {
        id: "consequence_banking_smart",
        type: "consequence",
        title: "Banking Postponed",
        description: "You decided to wait on banking...",
        location: "The Daily Grind Coffee Shop",
        consequence: {
          id: "cons_banking_smart",
          type: "action_postponed",
          severity: "success",
          title: "Excellent Judgment",
          whatHappened: "You recognized that banking is a high-sensitivity task and chose to postpone it until you're on a trusted network. This is exactly the right instinct.",
          whyRisky: "This was the ideal choice. There's no risk because you didn't expose your banking credentials on a public network.",
          saferAlternative: "You made the best possible decision. Banking should be reserved for trusted networks - your home Wi-Fi or mobile data connection.",
          technicalExplanation: "By postponing high-sensitivity tasks, you eliminate the attack surface entirely. This 'security by avoidance' is often the most effective approach for critical operations.",
          safetyPointsChange: 30,
          riskPointsChange: 0,
        },
        nextSceneId: "completion",
      },
      {
        id: "completion",
        type: "completion",
        title: "Scenario Complete",
        description: "You've completed the Coffee Shop Challenge! Let's review how you did.",
        location: "The Daily Grind Coffee Shop",
      },
    ],
  },
  {
    id: "hotel_intermediate",
    title: "Business Trip Hotel",
    description: "You're staying at a hotel for a business conference. The Wi-Fi situation is confusing, and you have important work to do before tomorrow's presentation.",
    location: "Grand Metropolitan Hotel",
    difficulty: "intermediate",
    estimatedTime: "7 minutes",
    startSceneId: "hotel_arrival",
    scenes: [
      {
        id: "hotel_arrival",
        type: "arrival",
        title: "Checking In",
        description: "You've just arrived at the Grand Metropolitan Hotel after a long flight. Tomorrow's presentation is crucial, and you need to review some documents and respond to emails tonight. The room has a desk and you're ready to work.",
        location: "Grand Metropolitan Hotel - Room 412",
        nextSceneId: "hotel_network_select",
      },
      {
        id: "hotel_network_select",
        type: "network_selection",
        title: "Hotel Wi-Fi Options",
        description: "Your laptop shows several networks. The hotel information card on the desk mentions 'complimentary Wi-Fi' but the network name is partially obscured by a coffee stain.",
        location: "Grand Metropolitan Hotel - Room 412",
        networks: [
          {
            id: "hotel_official",
            ssid: "GrandMetro_Guest",
            signalStrength: 5,
            isSecured: false,
            securityType: "open",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "suspicious",
            description: "Open network - typical for hotels with portal login",
          },
          {
            id: "hotel_premium",
            ssid: "GrandMetro_Premium",
            signalStrength: 5,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "safe",
            description: "Secured premium network - may require purchase",
          },
          {
            id: "hotel_fake",
            ssid: "Grand_Metropolitan_FREE",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "Suspicious - different naming convention",
          },
          {
            id: "hotel_conference",
            ssid: "Conference_Center",
            signalStrength: 3,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "suspicious",
            description: "Conference center network - may not be for guests",
          },
          {
            id: "personal_hotspot",
            ssid: "iPhone-John",
            signalStrength: 2,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "suspicious",
            description: "Someone's personal hotspot nearby",
          },
        ],
        actions: [
          { id: "call_desk", type: "verify_staff", label: "Call front desk to verify network", isPrimary: true },
        ],
        choices: [
          { actionId: "connect_hotel_official", nextSceneId: "hotel_portal" },
          { actionId: "connect_hotel_premium", nextSceneId: "hotel_premium_login" },
          { actionId: "connect_hotel_fake", nextSceneId: "hotel_consequence_trap" },
          { actionId: "call_desk", nextSceneId: "hotel_verified" },
        ],
      },
      {
        id: "hotel_portal",
        type: "captive_portal",
        title: "Captive Portal",
        description: "A login page appears. It asks for your room number and last name to authenticate. There's also a checkbox to 'Install our HotelConnect app for the best experience.'",
        location: "Grand Metropolitan Hotel - Room 412",
        actions: [
          { id: "login_only", type: "proceed", label: "Enter room info and login", isPrimary: true },
          { id: "login_and_install", type: "install_profile", label: "Login AND install the app", isDanger: true },
          { id: "use_vpn_portal", type: "use_vpn", label: "Login, then immediately enable VPN" },
          { id: "switch_network", type: "switch_network", label: "Go back and try a different network" },
        ],
        choices: [
          { actionId: "login_only", nextSceneId: "hotel_task_email" },
          { actionId: "login_and_install", nextSceneId: "hotel_consequence_app" },
          { actionId: "use_vpn_portal", nextSceneId: "hotel_task_email_vpn" },
          { actionId: "switch_network", nextSceneId: "hotel_network_select" },
        ],
      },
      {
        id: "hotel_verified",
        type: "network_selection",
        title: "Verified Information",
        description: "The front desk confirms: 'Our free Wi-Fi is GrandMetro_Guest - you'll need your room number and last name to log in. We also have GrandMetro_Premium for $15/night with faster speeds and better security.'",
        location: "Grand Metropolitan Hotel - Room 412",
        networks: [
          {
            id: "hotel_official_v",
            ssid: "GrandMetro_Guest",
            signalStrength: 5,
            isSecured: false,
            securityType: "open",
            isLegitimate: true,
            isTrap: false,
            verifiedByStaff: true,
            riskLevel: "suspicious",
            description: "Official free network - VERIFIED",
          },
          {
            id: "hotel_premium_v",
            ssid: "GrandMetro_Premium",
            signalStrength: 5,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            verifiedByStaff: true,
            riskLevel: "safe",
            description: "Official premium network - VERIFIED - $15/night",
          },
        ],
        choices: [
          { actionId: "connect_verified_guest", nextSceneId: "hotel_portal" },
          { actionId: "connect_verified_premium", nextSceneId: "hotel_premium_connected" },
        ],
      },
      {
        id: "hotel_premium_login",
        type: "task_prompt",
        title: "Premium Network",
        description: "The premium network requires a password. The hotel information card shows it costs $15/night but promises 'enterprise-grade security.'",
        location: "Grand Metropolitan Hotel - Room 412",
        task: {
          id: "premium_decision",
          type: "browse",
          title: "Premium Network Decision",
          description: "Decide whether to pay for the premium network or use the free option.",
          sensitivityLevel: "low",
        },
        actions: [
          { id: "pay_premium", type: "proceed", label: "Pay $15 for premium (call front desk)", isPrimary: true },
          { id: "use_free", type: "switch_network", label: "Use the free network instead" },
        ],
        choices: [
          { actionId: "pay_premium", nextSceneId: "hotel_premium_connected" },
          { actionId: "use_free", nextSceneId: "hotel_portal" },
        ],
      },
      {
        id: "hotel_premium_connected",
        type: "consequence",
        title: "Premium Connection",
        description: "You're connected to the premium network...",
        location: "Grand Metropolitan Hotel - Room 412",
        consequence: {
          id: "cons_premium",
          type: "safe_browsing",
          severity: "success",
          title: "Secure Choice",
          whatHappened: "You chose the premium, password-protected network. This provides encryption between your device and the access point, making it significantly harder for nearby attackers to intercept your traffic.",
          whyRisky: "This is a much safer choice than open networks. The only remaining risk is that the hotel could theoretically monitor traffic, but reputable hotels don't do this.",
          saferAlternative: "For maximum security, still use a VPN even on the premium network. But your choice was solid - paying for security is often worth it when doing sensitive work.",
          technicalExplanation: "WPA2 encryption protects data between your device and the router. Unlike open networks, an attacker can't simply capture and read packets without knowing the password.",
          safetyPointsChange: 20,
          riskPointsChange: 0,
        },
        nextSceneId: "hotel_task_presentation",
      },
      {
        id: "hotel_consequence_trap",
        type: "consequence",
        title: "Fake Hotel Network",
        description: "You connected to what you thought was the hotel's network...",
        location: "Grand Metropolitan Hotel - Room 412",
        consequence: {
          id: "cons_hotel_trap",
          type: "credential_harvested",
          severity: "danger",
          title: "Evil Twin Attack",
          whatHappened: "You connected to 'Grand_Metropolitan_FREE' - a fake network. Notice how it uses underscores instead of the hotel's camelCase naming? A fake login portal appeared and captured your room number, name, and the password you entered.",
          whyRisky: "Attackers specifically target hotels because guests are often tired from travel and in a hurry to connect. The slightly different network name was designed to seem legitimate while actually being a trap.",
          saferAlternative: "Always verify the exact network name with hotel staff. Pay attention to naming conventions - legitimate hotel networks usually follow a consistent pattern.",
          technicalExplanation: "This 'evil twin' attack is common in hotels. Attackers set up a fake network with a similar name and stronger signal. Guests connect, thinking it's legitimate, and all traffic passes through the attacker's device.",
          safetyPointsChange: 0,
          riskPointsChange: 35,
        },
        nextSceneId: "hotel_completion",
      },
      {
        id: "hotel_consequence_app",
        type: "consequence",
        title: "App Installation Request",
        description: "You installed the app the portal suggested...",
        location: "Grand Metropolitan Hotel - Room 412",
        consequence: {
          id: "cons_app",
          type: "malware_installed",
          severity: "danger",
          title: "Potentially Malicious App",
          whatHappened: "You installed an app from an unknown source. Even if this was a legitimate hotel app, installing software from captive portals is extremely risky. The app could have extensive permissions to access your data.",
          whyRisky: "Legitimate businesses rarely require app installation just to use Wi-Fi. This is a common tactic for installing monitoring software, adware, or malware. The 'app' could access your contacts, location, and other data.",
          saferAlternative: "Never install apps, profiles, or certificates from captive portals. If a business truly requires an app, download it directly from official app stores where it's been reviewed for security.",
          technicalExplanation: "Mobile device management (MDM) profiles and sideloaded apps can gain extensive access to your device - reading emails, tracking location, accessing files, and even capturing passwords.",
          safetyPointsChange: 0,
          riskPointsChange: 45,
        },
        nextSceneId: "hotel_completion",
      },
      {
        id: "hotel_task_email",
        type: "task_prompt",
        title: "Work Email",
        description: "You're connected to the hotel network. You need to check emails from your team about tomorrow's presentation.",
        location: "Grand Metropolitan Hotel - Room 412",
        task: {
          id: "hotel_email",
          type: "email",
          title: "Check Team Updates",
          description: "Review emails from your team with updates for tomorrow's presentation.",
          sensitivityLevel: "medium",
        },
        actions: [
          { id: "email_proceed", type: "proceed", label: "Check email now" },
          { id: "email_vpn", type: "use_vpn", label: "Enable VPN, then check", isPrimary: true },
        ],
        choices: [
          { actionId: "email_proceed", nextSceneId: "hotel_task_presentation" },
          { actionId: "email_vpn", nextSceneId: "hotel_task_presentation_vpn" },
        ],
      },
      {
        id: "hotel_task_email_vpn",
        type: "task_prompt",
        title: "VPN Active",
        description: "Your VPN is running. You can now check your emails securely.",
        location: "Grand Metropolitan Hotel - Room 412",
        task: {
          id: "hotel_email_vpn",
          type: "email",
          title: "Check Team Updates",
          description: "Review emails from your team with updates for tomorrow's presentation.",
          sensitivityLevel: "medium",
        },
        actions: [
          { id: "email_proceed_vpn", type: "proceed", label: "Check email (VPN protected)", isPrimary: true },
        ],
        choices: [
          { actionId: "email_proceed_vpn", nextSceneId: "hotel_task_presentation_vpn" },
        ],
      },
      {
        id: "hotel_task_presentation",
        type: "task_prompt",
        title: "Presentation Files",
        description: "You need to download an updated presentation file that your colleague shared via a cloud link.",
        location: "Grand Metropolitan Hotel - Room 412",
        task: {
          id: "download_pres",
          type: "download",
          title: "Download Updated Slides",
          description: "Download the updated presentation from the cloud sharing link in your email.",
          sensitivityLevel: "high",
          riskHint: "Downloaded files could be intercepted or modified on insecure networks.",
        },
        actions: [
          { id: "download_now", type: "proceed", label: "Download the file" },
          { id: "download_vpn", type: "use_vpn", label: "Enable VPN first", isPrimary: true },
          { id: "download_postpone", type: "postpone", label: "Use hotel business center instead" },
        ],
        choices: [
          { actionId: "download_now", nextSceneId: "hotel_consequence_download_risky" },
          { actionId: "download_vpn", nextSceneId: "hotel_consequence_download_vpn" },
          { actionId: "download_postpone", nextSceneId: "hotel_consequence_download_postponed" },
        ],
      },
      {
        id: "hotel_task_presentation_vpn",
        type: "task_prompt",
        title: "Presentation Files",
        description: "Your VPN is active. You need to download an updated presentation file.",
        location: "Grand Metropolitan Hotel - Room 412",
        task: {
          id: "download_pres_vpn",
          type: "download",
          title: "Download Updated Slides",
          description: "Download the updated presentation from the cloud sharing link.",
          sensitivityLevel: "high",
        },
        actions: [
          { id: "download_vpn_active", type: "proceed", label: "Download (VPN protected)", isPrimary: true },
        ],
        choices: [
          { actionId: "download_vpn_active", nextSceneId: "hotel_consequence_download_vpn" },
        ],
      },
      {
        id: "hotel_consequence_download_risky",
        type: "consequence",
        title: "Unprotected Download",
        description: "You downloaded the file on the open network...",
        location: "Grand Metropolitan Hotel - Room 412",
        consequence: {
          id: "cons_download_risky",
          type: "session_compromised",
          severity: "warning",
          title: "Risky File Transfer",
          whatHappened: "You downloaded files on an open hotel network without VPN protection. While cloud services use HTTPS, sophisticated attackers on hotel networks could potentially intercept or modify transfers.",
          whyRisky: "Open hotel networks are prime targets for attackers. Downloading work files exposes metadata and, in some attack scenarios, the files themselves could be tampered with.",
          saferAlternative: "Use a VPN when downloading any work files on public networks. Verify file integrity if your organization provides checksums. Consider using mobile data for sensitive transfers.",
          technicalExplanation: "While HTTPS protects content in transit, attackers could potentially perform SSL stripping attacks or compromise DNS to redirect to malicious servers.",
          safetyPointsChange: 0,
          riskPointsChange: 20,
        },
        nextSceneId: "hotel_completion",
      },
      {
        id: "hotel_consequence_download_vpn",
        type: "consequence",
        title: "Protected Download",
        description: "You downloaded the file with VPN protection...",
        location: "Grand Metropolitan Hotel - Room 412",
        consequence: {
          id: "cons_download_vpn",
          type: "vpn_protected",
          severity: "success",
          title: "Secure File Transfer",
          whatHappened: "You used VPN protection while downloading your work files. All traffic was encrypted through a secure tunnel, protecting both the files and metadata from potential attackers on the hotel network.",
          whyRisky: "You made the right choice. VPN protection on hotel networks is especially important because these are common targets for business travelers.",
          saferAlternative: "You did great! For extremely sensitive files, you might also verify file integrity using checksums if your organization provides them.",
          technicalExplanation: "The VPN encrypted all traffic between your device and the VPN server, making it impossible for local network attackers to intercept or modify your downloads.",
          safetyPointsChange: 25,
          riskPointsChange: 0,
        },
        nextSceneId: "hotel_completion",
      },
      {
        id: "hotel_consequence_download_postponed",
        type: "consequence",
        title: "Using Business Center",
        description: "You decided to use the hotel's business center...",
        location: "Grand Metropolitan Hotel - Business Center",
        consequence: {
          id: "cons_download_postponed",
          type: "action_postponed",
          severity: "success",
          title: "Cautious Choice",
          whatHappened: "You chose to use the hotel's business center, which typically has a wired connection and better security. This shows excellent security awareness.",
          whyRisky: "This was a safe choice. The trade-off is convenience - you had to leave your room. Business center computers may have their own risks (keyloggers, shared usage), so bring your own device if possible.",
          saferAlternative: "Using the business center's wired connection with your own laptop is often more secure than room Wi-Fi. Just be aware of physical security in shared spaces.",
          technicalExplanation: "Wired connections are generally more secure than wireless because they can't be intercepted over the air. However, they're still subject to network-level monitoring by the hotel.",
          safetyPointsChange: 15,
          riskPointsChange: 0,
        },
        nextSceneId: "hotel_completion",
      },
      {
        id: "hotel_completion",
        type: "completion",
        title: "Scenario Complete",
        description: "You've completed the Hotel Business Trip scenario! Let's see how well you navigated the hotel's network challenges.",
        location: "Grand Metropolitan Hotel",
      },
    ],
  },
  {
    id: "airport_advanced",
    title: "Airport Rush",
    description: "Your flight is delayed, you're stressed, and you absolutely must complete some urgent work. The airport has multiple Wi-Fi options, but time pressure is making you consider cutting corners.",
    location: "Metropolitan International Airport",
    difficulty: "advanced",
    estimatedTime: "8 minutes",
    startSceneId: "airport_arrival",
    scenes: [
      {
        id: "airport_arrival",
        type: "arrival",
        title: "Flight Delayed",
        description: "Your flight has been delayed by 2 hours. You're exhausted, stressed, and your phone is at 15% battery. Your boss just messaged that the client contract needs your signature TODAY, and there's a deadline in 45 minutes. You find a seat near an outlet.",
        location: "Metropolitan International Airport - Gate B7",
        nextSceneId: "airport_network_select",
      },
      {
        id: "airport_network_select",
        type: "network_selection",
        title: "Airport Networks",
        description: "Your laptop shows multiple networks. You're stressed about the deadline. There's an airport info kiosk nearby, but there's a line.",
        location: "Metropolitan International Airport - Gate B7",
        networks: [
          {
            id: "airport_official",
            ssid: "MetroAirport_Free",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "suspicious",
            description: "Official airport network - open with captive portal",
          },
          {
            id: "airport_lounge",
            ssid: "SkyLounge_Premium",
            signalStrength: 5,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "safe",
            description: "Airline lounge network - requires membership",
          },
          {
            id: "airport_fake_1",
            ssid: "Airport_Free_WiFi",
            signalStrength: 5,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "Strong signal, generic name - suspicious",
          },
          {
            id: "airport_fake_2",
            ssid: "MetroAirport-Guest",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: false,
            isTrap: true,
            riskLevel: "dangerous",
            description: "Similar name but with hyphen instead of underscore",
          },
          {
            id: "mobile_hotspot",
            ssid: "Use your mobile data",
            signalStrength: 3,
            isSecured: true,
            securityType: "wpa2",
            isLegitimate: true,
            isTrap: false,
            riskLevel: "safe",
            description: "Your phone's personal hotspot - uses cellular data",
          },
        ],
        actions: [
          { id: "wait_kiosk", type: "verify_staff", label: "Wait in line at info kiosk to verify" },
          { id: "use_mobile", type: "proceed", label: "Use mobile data hotspot instead", isPrimary: true },
        ],
        choices: [
          { actionId: "connect_airport_official", nextSceneId: "airport_portal" },
          { actionId: "connect_fake_1", nextSceneId: "airport_consequence_trap" },
          { actionId: "connect_fake_2", nextSceneId: "airport_consequence_trap_subtle" },
          { actionId: "wait_kiosk", nextSceneId: "airport_verified" },
          { actionId: "use_mobile", nextSceneId: "airport_mobile_connected" },
        ],
      },
      {
        id: "airport_mobile_connected",
        type: "consequence",
        title: "Mobile Data",
        description: "You enabled your phone's hotspot...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_mobile",
          type: "safe_browsing",
          severity: "success",
          title: "Excellent Decision Under Pressure",
          whatHappened: "Despite the time pressure, you chose to use your mobile data hotspot instead of potentially risky airport Wi-Fi. This is the most secure option available to you right now.",
          whyRisky: "Using mobile data is generally safer than public Wi-Fi because the connection goes directly to your carrier's network, bypassing all local network risks.",
          saferAlternative: "You made the optimal choice! Mobile data is almost always more secure than public Wi-Fi, especially in high-risk environments like airports where attackers specifically target stressed travelers.",
          technicalExplanation: "Mobile data connections are encrypted between your device and the cell tower using strong encryption. There's no local network for attackers to exploit.",
          safetyPointsChange: 30,
          riskPointsChange: 0,
        },
        nextSceneId: "airport_task_contract",
      },
      {
        id: "airport_portal",
        type: "captive_portal",
        title: "Airport Portal",
        description: "The airport's portal loads. It shows ads and asks you to accept terms. There's an option to 'Connect faster by downloading our Airport Companion app' and a 'Premium High-Speed Access' for $8.",
        location: "Metropolitan International Airport - Gate B7",
        actions: [
          { id: "accept_terms", type: "proceed", label: "Accept terms and connect (free)" },
          { id: "download_app", type: "install_profile", label: "Download app for faster connection", isDanger: true },
          { id: "pay_premium", type: "proceed", label: "Pay $8 for premium access", isPrimary: true },
          { id: "use_mobile_instead", type: "switch_network", label: "Switch to mobile data instead" },
        ],
        choices: [
          { actionId: "accept_terms", nextSceneId: "airport_task_contract_risky" },
          { actionId: "download_app", nextSceneId: "airport_consequence_app" },
          { actionId: "pay_premium", nextSceneId: "airport_task_contract" },
          { actionId: "use_mobile_instead", nextSceneId: "airport_mobile_connected" },
        ],
      },
      {
        id: "airport_verified",
        type: "network_selection",
        title: "Info Kiosk Confirmation",
        description: "After waiting 10 minutes (your deadline is now 35 minutes away), the staff confirms: 'Our official network is MetroAirport_Free with an underscore. Be careful - we've had reports of fake networks. The SkyLounge network is only for lounge members.'",
        location: "Metropolitan International Airport - Gate B7",
        networks: [
          {
            id: "airport_official_v",
            ssid: "MetroAirport_Free",
            signalStrength: 4,
            isSecured: false,
            securityType: "open",
            isLegitimate: true,
            isTrap: false,
            verifiedByStaff: true,
            riskLevel: "suspicious",
            description: "Official airport network - VERIFIED",
          },
        ],
        choices: [
          { actionId: "connect_verified_airport", nextSceneId: "airport_portal" },
        ],
      },
      {
        id: "airport_consequence_trap",
        type: "consequence",
        title: "Generic Trap Network",
        description: "You connected to 'Airport_Free_WiFi'...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_airport_trap",
          type: "credential_harvested",
          severity: "danger",
          title: "Attacker's Network",
          whatHappened: "You connected to a network with a suspiciously generic name and unusually strong signal. This was a portable hotspot set up by an attacker specifically to target stressed travelers.",
          whyRisky: "Time pressure made you rush your decision. Airports are high-value targets because travelers are often distracted and in a hurry. Generic names like 'Airport_Free_WiFi' are common attack vectors.",
          saferAlternative: "Even under time pressure, take 30 seconds to verify the official network name. Look for posted signs or check the airport's official website using mobile data first.",
          technicalExplanation: "Attackers use high-gain antennas to broadcast strong signals, making their fake networks appear as the 'best' connection. All your traffic then flows through their device.",
          safetyPointsChange: 0,
          riskPointsChange: 40,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_consequence_trap_subtle",
        type: "consequence",
        title: "Subtle Naming Trap",
        description: "You connected to 'MetroAirport-Guest'...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_airport_subtle",
          type: "credential_harvested",
          severity: "danger",
          title: "Careful Imitation",
          whatHappened: "You connected to 'MetroAirport-Guest' which looked legitimate at first glance. The real network uses an underscore (MetroAirport_Free), but this fake uses a hyphen and says 'Guest' instead of 'Free'.",
          whyRisky: "This is a sophisticated attack that exploits the small differences people overlook when rushed. The attacker knew the official network name and created a convincing variation.",
          saferAlternative: "Check the exact network name character by character. In airports, even one wrong character could mean you're connecting to an attacker's network.",
          technicalExplanation: "Attackers research target locations to create convincing fake network names. They rely on users not noticing small differences like hyphens vs. underscores or 'Guest' vs. 'Free'.",
          safetyPointsChange: 0,
          riskPointsChange: 35,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_consequence_app",
        type: "consequence",
        title: "App Installation",
        description: "You downloaded the 'Airport Companion' app...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_airport_app",
          type: "malware_installed",
          severity: "danger",
          title: "Suspicious App Installed",
          whatHappened: "Under time pressure, you installed an app from a captive portal. Even if this was a legitimate airport app, installing apps this way bypasses app store security reviews.",
          whyRisky: "Legitimate airports don't require app installation for Wi-Fi access. This app could contain tracking software, adware, or worse. The time pressure made you skip your usual caution.",
          saferAlternative: "Never install apps from captive portals. If you really want an airport's app, download it from the official app store BEFORE you need it, not in a rushed moment.",
          technicalExplanation: "Apps installed outside official stores bypass security scanning and could request excessive permissions. Under time pressure, users often grant all permissions without reading them.",
          safetyPointsChange: 0,
          riskPointsChange: 45,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_task_contract",
        type: "task_prompt",
        title: "Urgent Contract",
        description: "You're connected. The contract signing deadline is in 30 minutes. The document requires your digital signature.",
        location: "Metropolitan International Airport - Gate B7",
        task: {
          id: "contract_sign",
          type: "payment",
          title: "Sign Client Contract",
          description: "Open the secure document portal and digitally sign the client contract before the deadline.",
          sensitivityLevel: "critical",
          riskHint: "Digital signatures are legally binding and use your credentials.",
        },
        actions: [
          { id: "sign_now", type: "proceed", label: "Sign the contract now", isDanger: true },
          { id: "sign_vpn", type: "use_vpn", label: "Enable VPN, then sign", isPrimary: true },
          { id: "call_client", type: "postpone", label: "Call client to request deadline extension" },
        ],
        choices: [
          { actionId: "sign_now", nextSceneId: "airport_consequence_sign_risky" },
          { actionId: "sign_vpn", nextSceneId: "airport_consequence_sign_vpn" },
          { actionId: "call_client", nextSceneId: "airport_consequence_sign_delayed" },
        ],
      },
      {
        id: "airport_task_contract_risky",
        type: "task_prompt",
        title: "Urgent Contract",
        description: "You're on the free airport network without VPN. The contract deadline is in 25 minutes.",
        location: "Metropolitan International Airport - Gate B7",
        task: {
          id: "contract_sign_risky",
          type: "payment",
          title: "Sign Client Contract",
          description: "Sign the contract on this unprotected network?",
          sensitivityLevel: "critical",
          riskHint: "You're on an open network with many potential threats.",
        },
        actions: [
          { id: "sign_anyway", type: "proceed", label: "Sign now - no time!", isDanger: true },
          { id: "enable_vpn_late", type: "use_vpn", label: "Enable VPN first" },
          { id: "switch_mobile", type: "switch_network", label: "Switch to mobile data", isPrimary: true },
        ],
        choices: [
          { actionId: "sign_anyway", nextSceneId: "airport_consequence_sign_risky" },
          { actionId: "enable_vpn_late", nextSceneId: "airport_consequence_sign_vpn" },
          { actionId: "switch_mobile", nextSceneId: "airport_mobile_connected" },
        ],
      },
      {
        id: "airport_consequence_sign_risky",
        type: "consequence",
        title: "Unprotected Signature",
        description: "You signed the contract on the open network...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_sign_risky",
          type: "session_compromised",
          severity: "danger",
          title: "High-Risk Legal Action",
          whatHappened: "You signed a legally binding document on an open airport network. While the signing portal likely uses HTTPS, sophisticated attackers in airports could potentially intercept or forge this transaction.",
          whyRisky: "Digital signatures involve authentication credentials that could be valuable to attackers. Airports are known hotspots for corporate espionage targeting business travelers.",
          saferAlternative: "For legally binding documents, use mobile data or VPN. If possible, request deadline extensions rather than compromising security on critical transactions.",
          technicalExplanation: "Even with HTTPS, session hijacking attacks, malicious proxy configurations, or compromised certificates could potentially expose your signing credentials on open networks.",
          safetyPointsChange: 0,
          riskPointsChange: 40,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_consequence_sign_vpn",
        type: "consequence",
        title: "Protected Signature",
        description: "You enabled VPN before signing...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_sign_vpn",
          type: "vpn_protected",
          severity: "success",
          title: "Secure Under Pressure",
          whatHappened: "Despite the time pressure, you took the extra minute to enable VPN protection before signing the contract. This significantly reduced the risk of credential theft or session hijacking.",
          whyRisky: "You made the right choice. Even though it cost a minute, the VPN encryption protects your legally binding transaction from local network attacks.",
          saferAlternative: "You did well! For maximum security on critical legal documents, mobile data is still preferable to any public Wi-Fi, even with VPN.",
          technicalExplanation: "VPN encryption ensures that even if an attacker is monitoring the network, your signing session is encrypted end-to-end and cannot be intercepted or modified.",
          safetyPointsChange: 30,
          riskPointsChange: 0,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_consequence_sign_delayed",
        type: "consequence",
        title: "Deadline Extension",
        description: "You called the client...",
        location: "Metropolitan International Airport - Gate B7",
        consequence: {
          id: "cons_sign_delayed",
          type: "action_postponed",
          severity: "success",
          title: "Professional Judgment",
          whatHappened: "You called the client to explain the situation and requested a deadline extension. They agreed to extend by 4 hours until you reach a secure network. This protected both you and the client.",
          whyRisky: "This was an excellent decision. It required courage to ask for an extension, but it's better than compromising a legal document. Most clients appreciate security-conscious partners.",
          saferAlternative: "You made the optimal choice for a high-stakes situation. Explaining security concerns to clients demonstrates professionalism and protects both parties.",
          technicalExplanation: "By postponing the transaction, you eliminated all network-based risks entirely. For legally binding documents, this 'zero risk' approach is often the wisest choice.",
          safetyPointsChange: 35,
          riskPointsChange: 0,
        },
        nextSceneId: "airport_completion",
      },
      {
        id: "airport_completion",
        type: "completion",
        title: "Scenario Complete",
        description: "You've completed the Airport Rush scenario! This was the most challenging test of your judgment under pressure.",
        location: "Metropolitan International Airport",
      },
    ],
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return scenarios.find(s => s.id === id);
}

export function getScenariosByDifficulty(difficulty: string): Scenario[] {
  return scenarios.filter(s => s.difficulty === difficulty);
}
